version: '3.4'

services:
  synapse.api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: synapse-api
    build:
      context: .
      dockerfile: src/backend/Web.Api/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://synapse.dashboard:18889
    networks:
      - otel
 
  synapse.api1:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: synapse-api1
    build:
      context: .
      dockerfile: src/backend/Web.Api/Dockerfile
    ports:
      - 6000:6000
      - 6001:6001
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://synapse.dashboard:18889
    networks:
      - otel

  synapse.api2:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: synapse-api2
    build:
      context: .
      dockerfile: src/backend/Web.Api/Dockerfile
    ports:
      - 7000:7000
      - 7001:7001
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://synapse.dashboard:18889
    networks:
      - otel

  synapse-database:
    image: postgres:latest
    container_name: synapse.database
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - otel

  synapse-seq:
    image: datalust/seq:latest
    container_name: synapse.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  synapse-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: synapse.blob-storage
    volumes:
      - ./.containers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"
    networks:
      - otel

  synapse-redis:
    image: redis:latest
    container_name: synapse.redis
    restart: always
    ports:
      - 6379:6379 
    networks:
      - otel

  synapse.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: synapse.dashboard
    ports:
      - 18888:18888
    networks:
      - otel

networks:
  otel:
    