export enum QUERY_KEYS {
  GET_POSTS = "GET_POSTS",
  GET_POST_BY_ID = "GET_POST_BY_ID",
  INFINITE_POSTS = "INFINITE_POSTS",
  GET_SEARCH_POSTS = "GET_SEARCH_POSTS",

  GET_POST_COMMENTS = "GET_POST_COMMENTS",

  GET_POST_LIKES = "GET_POSTS_LIKES",

  GET_USER_FROM_AUTH = "GET_USER_FROM_AUTH",
  GET_USERS = "GET_USERS",
  GET_USER_FOLLOWER_STATS = "GET_USER_FOLLOWER_STATS",
  GET_USER_BY_ID = "GET_USER_BY_ID",
  GET_USER_POSTS = "GET_USER_POSTS",
}
